---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`petal_width` y `petal_length` est치n altamente correlacionadas"
  checked: true
- value: "`sepal_width` y `sepal_length` est치n altamente correlacionadas"
  checked: false
- value: "`sepal_length` y `petal_width` est치n altamente correlacionadas"
  checked: false
- value: "`petal_length` y `sepal_length` est치n correlacionadas"
  checked: true
name: Relacionando todo
